title: Semantic Segmentation with Polygons
type: community
group: Vision Analytics
order: 1
image: /static/templates/semantic-segmentation-with-polygons.png
details: <h1>Draw a polygon around object</h1>
config: |
  <View>

    <Header value="Select label and click the image to start"/>
    <Image name="image" value="$image" zoom="true"/>

    <PolygonLabels name="label" toName="image"
                   strokeWidth="3" pointSize="small"
                   opacity="0.9">
      <Label value="Airplane" background="red"/>
      <Label value="Car" background="blue"/>
    </PolygonLabels>

  </View>
